### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by KuanchihHuang** [xinshuoweng/AIODrive#1]
Thanks for your awesome dataset.
I found that there is only a mini version dataset on the website.
Do you have any plan to release the full dataset?
Thank you!

**Comment by xinshuoweng** [comment]
Hi,

Thanks for reaching out! In fact, the full dataset is released. You will need to click "full dataset" on the website to expand it and then you can see the download link. Sorry for the confusion, maybe we should change to "expanded" by default.
